=begin
#Vehicle Enquiry API

#Interface specification for the DVLA Vehicle Enquiry API

The version of the OpenAPI document: 1.1.0
Contact: DvlaAPIAccess@dvla.gov.uk
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for VesAPIClient::VehicleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VehicleApi' do
  before do
    # run before each test
    @api_instance = VesAPIClient::VehicleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VehicleApi' do
    it 'should create an instance of VehicleApi' do
      expect(@api_instance).to be_instance_of(VesAPIClient::VehicleApi)
    end
  end

  # unit tests for get_vehicle_details_by_registration_number
  # Get vehicle details by registration number
  # Returns vehicle details based on registration number
  # @param x_api_key Client Specific API Key
  # @param vehicle_request Registration number of the vehicle to find details for
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_correlation_id Consumer Correlation ID
  # @return [Vehicle]
  describe 'get_vehicle_details_by_registration_number test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
