=begin
#Vehicle Enquiry API

#Interface specification for the DVLA Vehicle Enquiry API

The version of the OpenAPI document: 1.1.0
Contact: DvlaAPIAccess@dvla.gov.uk
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VesAPIClient::VehicleRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VehicleRequest' do
  before do
    # run before each test
    @instance = VesAPIClient::VehicleRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VehicleRequest' do
    it 'should create an instance of VehicleRequest' do
      expect(@instance).to be_instance_of(VesAPIClient::VehicleRequest)
    end
  end
  describe 'test attribute "registration_number"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
