=begin
#Vehicle Enquiry API

#Interface specification for the DVLA Vehicle Enquiry API

The version of the OpenAPI document: 1.1.0
Contact: DvlaAPIAccess@dvla.gov.uk
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'vesapi_client/api_client'
require 'vesapi_client/api_error'
require 'vesapi_client/version'
require 'vesapi_client/configuration'

# Models
require 'vesapi_client/models/error_response'
require 'vesapi_client/models/errors'
require 'vesapi_client/models/vehicle'
require 'vesapi_client/models/vehicle_request'

# APIs
require 'vesapi_client/api/vehicle_api'

module VesAPIClient
  class << self
    # Customize default settings for the SDK using block.
    #   VesAPIClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
